services:
  # Allow running integration tests outside the docker network.
  sd-submit-api-csc:
    environment:
      - "BASE_URL=http://localhost:5430"
    ports:
      - "5430:5430"
  # Allow running integration tests outside the docker network.
  sd-submit-api-nbis:
    environment:
      - "BASE_URL=http://localhost:5431"
    ports:
      - "5431:5431"
  mock-oauth2:
    ports:
      - "8001:8001"
  mockauth:
    ports:
      - "8000:8000"
  mockkeystone:
    ports:
      - "5001:5001"
  # Allow connecting to the database outside the docker network.
  postgres-csc:
    ports:
      - "5432:5432"
  # Allow connecting to the database outside the docker network.
  postgres-nbis:
    ports:
      - "5433:5432"
