services:
  sd-submit-api:
    ports:
      - "5430:5430"
  mockauth:
    environment:
      - "OIDC_URL_TEST=${OIDC_URL_TEST}"
    ports:
      - "8000:8000"
  mockkeystone:
    ports:
      - "5001:5001"
  postgres:
    ports:
      - "5432:5432"
