services:
  # Allow running integration tests outside the docker network.
  sd-submit-api-csc:
    ports:
      - "5430:5430"
  # Allow running integration tests outside the docker network.
  sd-submit-api-nbis:
    ports:
      - "5431:5431"
  mockauth:
    environment:
      - "OIDC_URL_TEST=${OIDC_URL_TEST}"
    ports:
      - "8000:8000"
  mockkeystone:
    ports:
      - "5001:5001"
  # Allow connecting to the database outside the docker network.
  postgres-csc:
    ports:
      - "5432:5432"
  # Allow connecting to the database outside the docker network.
  postgres-nbis:
    ports:
      - "5433:5432"
