services:
  sd-submit-api-csc:
    ports:
      - "5430:5430"
  sd-submit-api-nbis:
    ports:
      - "5431:5431"
  mockauth:
    environment:
      - "OIDC_URL_TEST=${OIDC_URL_TEST}"
    ports:
      - "8000:8000"
  mockkeystone:
    ports:
      - "5001:5001"
  postgres:
    ports:
      - "5432:5432"
